### ISSUE TITLE
crash on startup

### ISSUE THREAD

**Issue by nc-gp** [DakotaPride/Boleatte#3]
hi, just as title says.
it's my custom modpack on quilt 0.17.6

[latest.log](https://github.com/DakotaPride/Boleatte/files/9951648/latest.log)
[crash-2022-11-07_13.38.52-client.txt](https://github.com/DakotaPride/Boleatte/files/9951652/crash-2022-11-07_13.38.52-client.txt)

thanks

**Comment by DakotaPride** [comment]
I think I may have fixed it, here's a dev build for it. If it still doesn't work, then it may have something to do with Quilted Fabric API, as I use 'custom portal API', which is developed for Fabric. Either way, please let me know if you have any other questions/concerns!

https://github.com/DakotaPride/Boleatte/releases/tag/v0.2.2-dev

**Comment by nc-gp** [comment]
> If it still doesn't work, then it may have something to do with Quilted Fabric API, as I use 'custom portal API', which is developed for Fabric.
> 
> https://github.com/DakotaPride/Boleatte/releases/tag/v0.2.2-dev

yeah, still crashing :/ you can try to make an version specifically for quilt or something
[crash-2022-11-07_14.53.57-client.txt](https://github.com/DakotaPride/Boleatte/files/9952227/crash-2022-11-07_14.53.57-client.txt)

edit 1. ~~quilt developer said that might be an loader issue~~

edit 2. boalette works with quilted fabric api (2 mods only)

edit 3. boalette is not compatible with deeper and darker

**Comment by DakotaPride** [comment]
I've taken a closer look and I'm actually not sure. What loader are you using to launch this modpack, if you don't mind me asking? (I just used Prism Launcher, with the modslist just being quilted fabric API and boleatte, and it worked just fine. There may be a compatibility issue with one of the other mods you're using)

**Comment by nc-gp** [comment]
> I've taken a closer look and I'm actually not sure. What loader are you using to launch this modpack, if you don't mind me asking? (I just used Prism Launcher, with the modslist just being quilted fabric API and boleatte, and it worked just fine. There may be a compatibility issue with one of the other mods you're using)

Multi MC

**Comment by DakotaPride** [comment]
What's the modpack name (if it's already released/has an available version)? If it's not released, then can I have a full modslist?

**Comment by nc-gp** [comment]
> What's the modpack name (if it's already released/has an available version)? If it's not released, then can I have a full modslist?

it's not released. but i think i found an issue, try to load deeper and darker and boleatte. i tried and modpack loads fine with boleatte and without deeper and darker.

**Comment by DakotaPride** [comment]
It seems to be incompatible with deeper and darker then, though I'm not sure why or how. I'll make sure to contact their team to see if we can get this issue resolved, thank you for your patience!

**Comment by DakotaPride** [comment]
Hello! Sorry for the wait, but it seems (according to one of the 'Deeper And Darker' devs) that this issue is fixed as of the most recent version of 'Deeper And Darker'. If you are not on the most recent version already, I highly suggest updating it, as it may solve your issue. Please let me know if the issue persists or if there are any other problems that you encounter, again, thank you for your patience!

**Comment by nc-gp** [comment]
hi, i can tell it's not fixed, still crashes for me.

i have the lastet version of mods, you can make sure of this checking the logs
[crash-2022-11-10_18.04.53-client.txt](https://github.com/DakotaPride/Boleatte/files/9983143/crash-2022-11-10_18.04.53-client.txt)

am i missing something?

**Comment by DakotaPride** [comment]
Huh, strange. It also seems like it was an issue with other dimension-related mods (such as Paradise Lost, which was fixed in the most recent 'Deeper And Darker' version). I'll make sure to let their team know (again) that it seems to not be fixed still. I'll see if there's anything else I can do as well.

(I don't think you're missing anything btw)

**Comment by DakotaPride** [comment]
@rbl-dot 
Okay, after a few more days, the issue has been fixed (hopefully). [Here is a beta build for v2.2.2](https://github.com/DakotaPride/Boleatte/releases/tag/v0.2.2-dev2), keep in mind there are still more features to be added, but this is a version that has the bug fixed. Let me know if, somehow, it still doesn't work!
(needed to update custom portal API as a dependency)

![2022-11-13_16 10 28](https://user-images.githubusercontent.com/82760983/201547233-23b8f9ac-490d-4d22-aced-8b02e8fba99f.png)
